version: 2

project_name: bdy

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - main: ./cmd/bdy
    binary: bdy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.ShortCommit}}
      - -X main.Date={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: poiley
      name: homebrew-tap
    name: bdy
    homepage: "https://github.com/poiley/beady"
    description: "A k9s-style terminal UI for browsing beads issues"
    license: "MIT"
    install: |
      bin.install "bdy"
    test: |
      system "#{bin}/bdy", "--version"

release:
  github:
    owner: poiley
    name: beady
  draft: false
  prerelease: auto
